# Build context: raiz do repositório Tecnica/
FROM mcr.microsoft.com/dotnet/sdk:8.0-jammy AS build
WORKDIR /src

COPY AntiFraud/AntiFraud.sln AntiFraud/
COPY AntiFraud/src/AntiFraud.Domain/AntiFraud.Domain.csproj AntiFraud/src/AntiFraud.Domain/
COPY AntiFraud/src/AntiFraud.Application/AntiFraud.Application.csproj AntiFraud/src/AntiFraud.Application/
COPY AntiFraud/src/AntiFraud.Infrastructure/AntiFraud.Infrastructure.csproj AntiFraud/src/AntiFraud.Infrastructure/
COPY AntiFraud/src/AntiFraud.Worker/AntiFraud.Worker.csproj AntiFraud/src/AntiFraud.Worker/

RUN dotnet restore AntiFraud/src/AntiFraud.Worker/AntiFraud.Worker.csproj

COPY AntiFraud/src/ AntiFraud/src/
RUN dotnet publish AntiFraud/src/AntiFraud.Worker/AntiFraud.Worker.csproj -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/runtime:8.0-jammy AS final
WORKDIR /app

COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "AntiFraud.Worker.dll"]
